// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigManager handles loading, saving, and synchronizing config.toml and config.yaml.
 */
export interface ConfigManager {
}
