// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentDetail represents the detailed configuration state of a selected agent.
 */
export interface AgentDetail {
    "id": string;
    "claudeCode"?: ClaudeCodeConfig | null;
    "codex"?: CodexConfig | null;
    "model": string;
    "configured": boolean;
}

/**
 * AgentInfo represents discovery and integration state of an agent client.
 */
export interface AgentInfo {
    "id": string;
    "name": string;
    "executable": string;
    "format": string;
    "description": string;
    "installed": boolean;
    "cliInstalled": boolean;
    "version": string;
    "cliVersion": string;
    "appVersion": string;
    "executablePath": string;
    "configFound": boolean;
    "configured": boolean;
    "currentModel": string;
    "configPaths": string[] | null;
    "supportedModels": string[] | null;
    "warnings": string[] | null;
}

/**
 * ApiKeyEntry stores an API key with an optional user remark.
 */
export interface ApiKeyEntry {
    "apiKey": string;
    "remark": string;
}

/**
 * BackupEntry represents a configuration snapshot made before modifying a client.
 */
export interface BackupEntry {
    "id": string;
    "clientId": string;
    "createdAt": string;
    "timestampUnix": number;
    "filePath": string;
}

/**
 * ClaudeCodeConfig represents fine-grained configuration for Claude Code.
 */
export interface ClaudeCodeConfig {
    "opusModel": string;
    "sonnetModel": string;
    "haikuModel": string;
    "opus1M": boolean;
    "sonnet1M": boolean;
    "haiku1M": boolean;
    "maxContextTokens": number;
    "autoCompactPct": number;
    "disableAutoCompact": boolean;
    "customMapping": boolean;
}

/**
 * CodexConfig represents configuration for Codex CLI.
 */
export interface CodexConfig {
    "model": string;

    /**
     * "apikey" or "oauth"
     */
    "authMethod": string;
}

/**
 * CodexNativeStatus represents the state of Codex native OAuth vs CPA proxy mode.
 */
export interface CodexNativeStatus {
    "enabled": boolean;
    "officialAuthExists": boolean;
    "hasCpaConfig": boolean;
    "accountEmail"?: string | null;
}

/**
 * CoreInstallTask represents progress of an active install/update task.
 */
export interface CoreInstallTask {
    "running": boolean;
    "cancellable": boolean;
    "phase": string;
    "percentage": number;
    "downloadedBytes": number;
    "totalBytes": number;
    "error": string | null;
}

/**
 * CoreSettings represents kernel settings managed by GUI and stored in config.yaml.
 */
export interface CoreSettings {
    "host": string;
    "port": number;
    "authDir": string;
    "debug": boolean;
    "commercialMode": boolean;
    "loggingToFile": boolean;
    "logsMaxTotalSizeMb": number;
    "errorLogsMaxFiles": number;
    "usageStatisticsEnabled": boolean;
    "redisUsageQueueRetentionSeconds": number;
    "requestLog": boolean;
    "routingStrategy": string;
    "routingSessionAffinity": boolean;
    "routingSessionAffinityTtl": string;
    "disableCooling": boolean;
    "requestRetry": number;
    "maxRetryCredentials": number;
    "maxRetryInterval": number;
    "streamingBootstrapRetries": number;
    "proxyUrl": string;
    "proxyOverride": boolean;
    "allowLan": boolean;
}

/**
 * CoreStatus represents the runtime and installation state of the proxy core.
 */
export interface CoreStatus {
    "installed": boolean;
    "running": boolean;
    "ready": boolean;
    "starting": boolean;
    "managed": boolean;
    "processId": number | null;
    "currentVersion": string | null;
    "installDir": string;
    "binaryPath": string | null;
    "message": string;
}

/**
 * DailyTrendPoint represents daily usage data for charts.
 */
export interface DailyTrendPoint {
    "date": string;
    "requests": number;
    "promptTokens": number;
    "completionTokens": number;
    "totalTokens": number;
    "cost": number;
}

/**
 * GuiConfigFile is the complete representation stored in config.toml.
 */
export interface GuiConfigFile {
    "locale": string;
    "theme": string;
    "runOnStartup": boolean;
    "closeBehavior": string;
    "lightweightMode": boolean;
    "showTrayIcon": boolean;
    "downloadSource": string;
    "customDownloadMirrors": string[] | null;
    "host": string;
    "port": number;
    "authDir": string;
    "debug": boolean;
    "commercialMode": boolean;
    "loggingToFile": boolean;
    "logsMaxTotalSizeMb": number;
    "errorLogsMaxFiles": number;
    "usageStatisticsEnabled": boolean;
    "redisUsageQueueRetentionSeconds": number;
    "requestLog": boolean;
    "routingStrategy": string;
    "routingSessionAffinity": boolean;
    "routingSessionAffinityTtl": string;
    "disableCooling": boolean;
    "requestRetry": number;
    "maxRetryCredentials": number;
    "maxRetryInterval": number;
    "streamingBootstrapRetries": number;
    "proxyUrl": string;
    "proxyOverride": boolean;
    "allowLan": boolean;
    "apiKeys": ApiKeyEntry[] | null;
    "managementSecretKey"?: string;
}

/**
 * GuiSettings represents purely desktop/GUI settings stored in config.toml.
 */
export interface GuiSettings {
    "locale": string;
    "theme": string;
    "runOnStartup": boolean;
    "closeBehavior": string;
    "lightweightMode": boolean;
    "showTrayIcon": boolean;
    "downloadSource": string;
    "customDownloadMirrors": string[] | null;
}

/**
 * ManagementRequest represents an HTTP request to be forwarded to cpa-core's /v0/management/* API.
 */
export interface ManagementRequest {
    "method": string;
    "path": string;
    "query"?: { [_ in string]?: string } | null;
    "body"?: any;
    "timeoutMs"?: number | null;
}

/**
 * OAuthBrowserOption represents a detected browser choice for opening OAuth URLs.
 */
export interface OAuthBrowserOption {
    "id": string;
    "label": string;
}

/**
 * OAuthStartResult represents the response when starting an OAuth login flow.
 */
export interface OAuthStartResult {
    "url": string;
    "state"?: string | null;
    "opened": boolean;
    "openError"?: string | null;
}

/**
 * OAuthStatusResult represents the polling response of an OAuth authorization session.
 */
export interface OAuthStatusResult {
    /**
     * "ok" | "wait" | "error"
     */
    "status": string;
    "error"?: string | null;
}

/**
 * ReleaseAsset represents an asset in a core release.
 */
export interface ReleaseAsset {
    "name": string;
    "downloadUrl": string;
    "size": number;
    "sha256": string;
}

/**
 * ReleaseInfo contains release information discovered from GitHub or mirrors.
 */
export interface ReleaseInfo {
    "version": string;
    "tagName": string;
    "releaseNotes": string;
    "publishedAt": string;
    "assets": ReleaseAsset[] | null;
}

/**
 * UsageRecord represents an individual proxy request log entry with token metrics.
 */
export interface UsageRecord {
    "id": string;
    "timestamp": number;
    "timeFormatted": string;
    "model": string;
    "provider": string;
    "promptTokens": number;
    "completionTokens": number;
    "totalTokens": number;
    "durationMs": number;
    "statusCode": number;
    "cost": number;
}

/**
 * UsageSummary provides aggregated metrics across all or daily records.
 */
export interface UsageSummary {
    "totalRequests": number;
    "todayRequests": number;
    "totalPromptTokens": number;
    "totalCompletionTokens": number;
    "totalTokens": number;
    "totalCost": number;
    "todayCost": number;
}
