// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CoreInstallTask represents progress of an active install/update task.
 */
export interface CoreInstallTask {
    "running": boolean;
    "cancellable": boolean;
    "phase": string;
    "percentage": number;
    "downloadedBytes": number;
    "totalBytes": number;
    "error": string | null;
}

/**
 * CoreStatus represents the runtime and installation state of the proxy core.
 */
export interface CoreStatus {
    "installed": boolean;
    "running": boolean;
    "ready": boolean;
    "starting": boolean;
    "managed": boolean;
    "processId": number | null;
    "currentVersion": string | null;
    "installDir": string;
    "binaryPath": string | null;
    "message": string;
}

/**
 * ReleaseAsset represents an asset in a core release.
 */
export interface ReleaseAsset {
    "name": string;
    "downloadUrl": string;
    "size": number;
    "sha256": string;
}

/**
 * ReleaseInfo contains release information discovered from GitHub or mirrors.
 */
export interface ReleaseInfo {
    "version": string;
    "tagName": string;
    "releaseNotes": string;
    "publishedAt": string;
    "assets": ReleaseAsset[] | null;
}
