// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentInfo represents discovery and integration state of an agent client.
 */
export interface AgentInfo {
    "id": string;
    "name": string;
    "executable": string;
    "format": string;
    "description": string;
    "cliInstalled": boolean;
    "configFound": boolean;
    "configured": boolean;
    "currentModel": string;
    "configPaths": string[] | null;
    "supportedModels": string[] | null;
}

/**
 * ApiKeyEntry stores an API key with an optional user remark.
 */
export interface ApiKeyEntry {
    "apiKey": string;
    "remark": string;
}

/**
 * BackupEntry represents a configuration snapshot made before modifying a client.
 */
export interface BackupEntry {
    "id": string;
    "clientId": string;
    "createdAt": string;
    "timestampUnix": number;
    "filePath": string;
}

/**
 * CoreInstallTask represents progress of an active install/update task.
 */
export interface CoreInstallTask {
    "running": boolean;
    "cancellable": boolean;
    "phase": string;
    "percentage": number;
    "downloadedBytes": number;
    "totalBytes": number;
    "error": string | null;
}

/**
 * CoreSettings represents kernel settings managed by GUI and stored in config.yaml.
 */
export interface CoreSettings {
    "host": string;
    "port": number;
    "authDir": string;
    "debug": boolean;
    "commercialMode": boolean;
    "loggingToFile": boolean;
    "logsMaxTotalSizeMb": number;
    "errorLogsMaxFiles": number;
    "usageStatisticsEnabled": boolean;
    "redisUsageQueueRetentionSeconds": number;
    "requestLog": boolean;
    "routingStrategy": string;
    "routingSessionAffinity": boolean;
    "routingSessionAffinityTtl": string;
    "disableCooling": boolean;
    "requestRetry": number;
    "maxRetryCredentials": number;
    "maxRetryInterval": number;
    "streamingBootstrapRetries": number;
    "proxyUrl": string;
    "proxyOverride": boolean;
    "allowLan": boolean;
}

/**
 * CoreStatus represents the runtime and installation state of the proxy core.
 */
export interface CoreStatus {
    "installed": boolean;
    "running": boolean;
    "ready": boolean;
    "starting": boolean;
    "managed": boolean;
    "processId": number | null;
    "currentVersion": string | null;
    "installDir": string;
    "binaryPath": string | null;
    "message": string;
}

/**
 * GuiConfigFile is the complete representation stored in config.toml.
 */
export interface GuiConfigFile {
    "locale": string;
    "theme": string;
    "runOnStartup": boolean;
    "closeBehavior": string;
    "downloadSource": string;
    "customDownloadMirrors": string[] | null;
    "host": string;
    "port": number;
    "authDir": string;
    "debug": boolean;
    "commercialMode": boolean;
    "loggingToFile": boolean;
    "logsMaxTotalSizeMb": number;
    "errorLogsMaxFiles": number;
    "usageStatisticsEnabled": boolean;
    "redisUsageQueueRetentionSeconds": number;
    "requestLog": boolean;
    "routingStrategy": string;
    "routingSessionAffinity": boolean;
    "routingSessionAffinityTtl": string;
    "disableCooling": boolean;
    "requestRetry": number;
    "maxRetryCredentials": number;
    "maxRetryInterval": number;
    "streamingBootstrapRetries": number;
    "proxyUrl": string;
    "proxyOverride": boolean;
    "allowLan": boolean;
    "apiKeys": ApiKeyEntry[] | null;
    "managementSecretKey"?: string;
}

/**
 * ReleaseAsset represents an asset in a core release.
 */
export interface ReleaseAsset {
    "name": string;
    "downloadUrl": string;
    "size": number;
    "sha256": string;
}

/**
 * ReleaseInfo contains release information discovered from GitHub or mirrors.
 */
export interface ReleaseInfo {
    "version": string;
    "tagName": string;
    "releaseNotes": string;
    "publishedAt": string;
    "assets": ReleaseAsset[] | null;
}
