// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * ApplyAgentConfig configures the specified client with transaction and backup.
 */
export function ApplyAgentConfig(id: string, modelName: string): $CancellablePromise<void> {
    return $Call.ByID(583144902, id, modelName);
}

/**
 * GetAgent returns discovery status for a single agent.
 */
export function GetAgent(id: string): $CancellablePromise<model$0.AgentInfo> {
    return $Call.ByID(4234722684, id);
}

/**
 * ListAgents returns discovery status for all supported agent targets.
 */
export function ListAgents(): $CancellablePromise<model$0.AgentInfo[] | null> {
    return $Call.ByID(255089387);
}

/**
 * ListBackups returns all configuration backups for the specified client.
 */
export function ListBackups(id: string): $CancellablePromise<model$0.BackupEntry[] | null> {
    return $Call.ByID(503160880, id);
}

/**
 * RestoreAgentConfig restores the latest backup for the specified client.
 */
export function RestoreAgentConfig(id: string): $CancellablePromise<void> {
    return $Call.ByID(3384915492, id);
}

/**
 * RestoreSpecificBackup restores a specific historical backup.
 */
export function RestoreSpecificBackup(id: string, backupFileName: string): $CancellablePromise<void> {
    return $Call.ByID(183574175, id, backupFileName);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1592354134, app);
}
