// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * ApplyAgentConfig configures the specified client with transaction and backup.
 */
export function ApplyAgentConfig(id: string, modelName: string): $CancellablePromise<void> {
    return $Call.ByID(583144902, id, modelName);
}

/**
 * ApplyClaudeCodeConfig applies fine-grained Claude Code configuration.
 */
export function ApplyClaudeCodeConfig(options: model$0.ClaudeCodeConfig): $CancellablePromise<void> {
    return $Call.ByID(1912806366, options);
}

/**
 * ApplyCodexConfig applies fine-grained Codex configuration.
 */
export function ApplyCodexConfig(options: model$0.CodexConfig): $CancellablePromise<void> {
    return $Call.ByID(241264312, options);
}

/**
 * CheckCodexOAuthLogin checks if Codex has official OAuth credentials.
 */
export function CheckCodexOAuthLogin(): $CancellablePromise<boolean> {
    return $Call.ByID(4132307566);
}

/**
 * CloseAgentConfig removes CPA proxy configuration from the client.
 */
export function CloseAgentConfig(id: string): $CancellablePromise<void> {
    return $Call.ByID(1921184574, id);
}

/**
 * CloseCodexConfigModification removes CPA proxy settings from Codex config.toml.
 */
export function CloseCodexConfigModification(): $CancellablePromise<void> {
    return $Call.ByID(3141769068);
}

/**
 * GetAgent returns discovery status for a single agent.
 */
export function GetAgent(id: string): $CancellablePromise<model$0.AgentInfo> {
    return $Call.ByID(4234722684, id);
}

/**
 * GetAgentDetail returns detailed configuration parameters for an agent client.
 */
export function GetAgentDetail(id: string): $CancellablePromise<model$0.AgentDetail> {
    return $Call.ByID(2289978829, id);
}

/**
 * GetAvailableModels returns the list of candidate upstream models for agent selection.
 */
export function GetAvailableModels(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2890026240);
}

/**
 * GetCodexNativeStatus retrieves the status of Codex native mode and authentication.
 */
export function GetCodexNativeStatus(): $CancellablePromise<model$0.CodexNativeStatus> {
    return $Call.ByID(3321688735);
}

/**
 * LaunchAgent opens the agent client in system terminal or opens the app.
 */
export function LaunchAgent(id: string): $CancellablePromise<void> {
    return $Call.ByID(2068057491, id);
}

/**
 * ListAgents returns discovery status for all supported agent targets concurrently.
 */
export function ListAgents(): $CancellablePromise<model$0.AgentInfo[] | null> {
    return $Call.ByID(255089387);
}

/**
 * ListBackups returns all configuration backups for the specified client.
 */
export function ListBackups(id: string): $CancellablePromise<model$0.BackupEntry[] | null> {
    return $Call.ByID(503160880, id);
}

/**
 * RestoreAgentConfig restores the latest backup for the specified client.
 */
export function RestoreAgentConfig(id: string): $CancellablePromise<void> {
    return $Call.ByID(3384915492, id);
}

/**
 * RestoreCodexOfficialConfig resets Codex configuration to official native OpenAI mode.
 */
export function RestoreCodexOfficialConfig(): $CancellablePromise<void> {
    return $Call.ByID(3403428315);
}

/**
 * RestoreSpecificBackup restores a specific historical backup.
 */
export function RestoreSpecificBackup(id: string, backupFileName: string): $CancellablePromise<void> {
    return $Call.ByID(183574175, id, backupFileName);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1592354134, app);
}
