// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * GetApiKeys returns the list of API keys.
 */
export function GetApiKeys(): $CancellablePromise<model$0.ApiKeyEntry[] | null> {
    return $Call.ByID(1300990896);
}

/**
 * GetCoreSettings returns the core settings portion.
 */
export function GetCoreSettings(): $CancellablePromise<model$0.CoreSettings> {
    return $Call.ByID(3102591734);
}

/**
 * GetGuiConfig returns the complete config.toml.
 */
export function GetGuiConfig(): $CancellablePromise<model$0.GuiConfigFile> {
    return $Call.ByID(554931725);
}

/**
 * GetGuiSettings returns only the GUI/desktop settings portion.
 */
export function GetGuiSettings(): $CancellablePromise<model$0.GuiSettings> {
    return $Call.ByID(3830770930);
}

export function Manager(): $CancellablePromise<config$0.ConfigManager | null> {
    return $Call.ByID(1669922767);
}

/**
 * SaveApiKeys updates the list of API keys.
 */
export function SaveApiKeys(keys: model$0.ApiKeyEntry[] | null): $CancellablePromise<void> {
    return $Call.ByID(1870369375, keys);
}

/**
 * SaveCoreSettings updates only the core settings portion.
 */
export function SaveCoreSettings(settings: model$0.CoreSettings): $CancellablePromise<void> {
    return $Call.ByID(1741052579, settings);
}

/**
 * SaveGuiConfig persists the complete config.toml and synchronizes to config.yaml.
 */
export function SaveGuiConfig(cfg: model$0.GuiConfigFile): $CancellablePromise<void> {
    return $Call.ByID(1024464262, cfg);
}

/**
 * SaveGuiSettings updates only the GUI/desktop settings portion.
 */
export function SaveGuiSettings(settings: model$0.GuiSettings): $CancellablePromise<void> {
    return $Call.ByID(1860272469, settings);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2924516363, app);
}

/**
 * Teardown cleans up resources on shutdown.
 */
export function Teardown(): $CancellablePromise<void> {
    return $Call.ByID(3779456880);
}
