// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * CancelCoreInstall cancels an active installation task.
 */
export function CancelCoreInstall(): $CancellablePromise<void> {
    return $Call.ByID(1790205571);
}

/**
 * CheckHealth performs an active end-to-end HTTP health probe against the proxy core.
 */
export function CheckHealth(): $CancellablePromise<model$0.CoreHealthCheck> {
    return $Call.ByID(9764129);
}

/**
 * CheckLatestCore checks the latest release from the specified source.
 */
export function CheckLatestCore(source: string): $CancellablePromise<model$0.ReleaseInfo | null> {
    return $Call.ByID(2942012851, source);
}

/**
 * GetCoreInstallTask returns the active or last install task.
 */
export function GetCoreInstallTask(): $CancellablePromise<model$0.CoreInstallTask> {
    return $Call.ByID(3805023694);
}

/**
 * GetCorePort reads the port from config.yaml or returns default 8317.
 */
export function GetCorePort(): $CancellablePromise<number> {
    return $Call.ByID(2176214871);
}

/**
 * GetStatus returns the current status of the core.
 */
export function GetStatus(): $CancellablePromise<model$0.CoreStatus> {
    return $Call.ByID(101457329);
}

/**
 * InstallCoreVersion downloads and installs the specified core version.
 */
export function InstallCoreVersion(version: string, source: string): $CancellablePromise<void> {
    return $Call.ByID(4179248161, version, source);
}

/**
 * RestartCore restarts the core process.
 */
export function RestartCore(): $CancellablePromise<void> {
    return $Call.ByID(3448596251);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(211482854, app);
}

/**
 * StartCore starts the core process.
 */
export function StartCore(): $CancellablePromise<void> {
    return $Call.ByID(3018840628);
}

/**
 * StopCore stops the core process.
 */
export function StopCore(): $CancellablePromise<void> {
    return $Call.ByID(1460723278);
}

/**
 * Teardown cleans up child processes on app exit.
 */
export function Teardown(): $CancellablePromise<void> {
    return $Call.ByID(3996267297);
}
