// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DesktopService exposes desktop window management and lifecycle methods to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * EnterLightweightMode destroys the WebUI window to release WebKit memory,
 * leaving the proxy core and menu bar tray running in the background.
 */
export function EnterLightweightMode(): $CancellablePromise<void> {
    return $Call.ByID(140809589);
}

/**
 * HideWindow minimizes/hides the main window to the system tray.
 */
export function HideWindow(): $CancellablePromise<void> {
    return $Call.ByID(2126967000);
}

/**
 * IsLightweightModeEnabled checks if lightweight mode is currently enabled in settings.
 */
export function IsLightweightModeEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(2191469944);
}

/**
 * QuitApp shuts down the application and cleanly terminates all background processes.
 */
export function QuitApp(): $CancellablePromise<void> {
    return $Call.ByID(1134489526);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2790661455, app);
}

export function SetWindowManager(wm: $models.WindowManager | null): $CancellablePromise<void> {
    return $Call.ByID(940909103, wm);
}

/**
 * ShowWindow shows and focuses the main window.
 */
export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(2592687749);
}
