// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowManager coordinates the lifecycle of the primary WebviewWindow,
 * including creating on demand, hiding, and releasing the WebKit rendering
 * process when lightweight mode is engaged.
 */
export interface WindowManager {
}
