// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * GetOAuthStatus queries the current status of an ongoing OAuth login session.
 */
export function GetOAuthStatus(state: string): $CancellablePromise<model$0.OAuthStatusResult> {
    return $Call.ByID(2571923754, state);
}

/**
 * ListOAuthBrowsers returns the available browsers on the host system.
 */
export function ListOAuthBrowsers(): $CancellablePromise<model$0.OAuthBrowserOption[] | null> {
    return $Call.ByID(3069074235);
}

/**
 * ManagementRequest proxies arbitrary requests to /v0/management/* on cpa-core.
 */
export function ManagementRequest(req: model$0.ManagementRequest): $CancellablePromise<any> {
    return $Call.ByID(3912550125, req);
}

/**
 * OpenAuthFilesDirectory opens the local oauth directory in the system file manager.
 */
export function OpenAuthFilesDirectory(): $CancellablePromise<void> {
    return $Call.ByID(1303057371);
}

/**
 * OpenCoreLogsDirectory opens the local core logs directory in the system file manager.
 */
export function OpenCoreLogsDirectory(): $CancellablePromise<void> {
    return $Call.ByID(3830370506);
}

/**
 * OpenOAuthUrl opens an authorization URL in the specified browser.
 */
export function OpenOAuthUrl(urlStr: string, browser: string): $CancellablePromise<void> {
    return $Call.ByID(2625211883, urlStr, browser);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3228222508, app);
}

/**
 * StartOAuthLogin initiates an OAuth login flow with cpa-core.
 */
export function StartOAuthLogin(provider: string, browser: string): $CancellablePromise<model$0.OAuthStartResult> {
    return $Call.ByID(1800110201, provider, browser);
}

/**
 * SubmitOAuthCallback sends a manual callback code/URL to cpa-core.
 */
export function SubmitOAuthCallback(provider: string, redirectUrl: string): $CancellablePromise<void> {
    return $Call.ByID(2765027913, provider, redirectUrl);
}

/**
 * UploadAuthFile uploads a credential JSON file to cpa-core via management API.
 */
export function UploadAuthFile(name: string, dataBase64: string): $CancellablePromise<any> {
    return $Call.ByID(1952094078, name, dataBase64);
}
