// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * ManagementRequest proxies arbitrary requests to /v0/management/* on cpa-core.
 */
export function ManagementRequest(req: model$0.ManagementRequest): $CancellablePromise<any> {
    return $Call.ByID(2994726037, req);
}

/**
 * ProviderHealthProbe sends a test probe request with streaming enabled to measure latency.
 */
export function ProviderHealthProbe(req: model$0.ProviderHealthProbeRequest): $CancellablePromise<model$0.ProviderHealthProbeResponse> {
    return $Call.ByID(1510905078, req);
}

/**
 * ResolveApiAccessRemarks resolves remarks for a batch of provider locators from config.toml.
 */
export function ResolveApiAccessRemarks(queries: model$0.ApiAccessRemarkQuery[] | null): $CancellablePromise<string[] | null> {
    return $Call.ByID(2512236762, queries);
}

/**
 * SaveApiAccessRemark saves or updates the remark for a provider in config.toml.
 */
export function SaveApiAccessRemark(update: model$0.ApiAccessRemarkUpdate): $CancellablePromise<void> {
    return $Call.ByID(1518182652, update);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2064978052, app);
}
