// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * GetDailyTrend returns daily aggregated data for the last N days.
 */
export function GetDailyTrend(days: number): $CancellablePromise<model$0.DailyTrendPoint[] | null> {
    return $Call.ByID(3826069265, days);
}

/**
 * GetRecentRecords returns a paginated list of recent requests.
 */
export function GetRecentRecords(limit: number, offset: number): $CancellablePromise<model$0.UsageRecord[] | null> {
    return $Call.ByID(798139856, limit, offset);
}

/**
 * GetUsageSummary returns the aggregated usage metrics.
 */
export function GetUsageSummary(): $CancellablePromise<model$0.UsageSummary> {
    return $Call.ByID(2772784328);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2594614384, app);
}

/**
 * Teardown closes background collector and database.
 */
export function Teardown(): $CancellablePromise<void> {
    return $Call.ByID(729101647);
}

/**
 * TriggerSync updates collector configuration and syncs records.
 */
export function TriggerSync(): $CancellablePromise<void> {
    return $Call.ByID(1372206482);
}
